#!/bin/sh
#THIS IS A GRUB PROXY SCRIPT
'/etc/grub.d/proxifiedScripts/linux' | /etc/grub.d/bin/grubcfg_proxy "-*
-#text
-'Arch Linux'~88ffed2813ade90a49382454b9d54818~
-'SUBMENU' as 'Recovery...'{-'Advanced options for Arch Linux'/*}
+'Advanced options for Arch Linux'/'Arch Linux, with Linux linux (recovery mode)'~092fa46bd2174ecabb4f47943db394db~
+'Advanced options for Arch Linux'/'Arch Linux, with Linux linux'~07823ca2cafd438a4161745a01cdd44c~
+'Advanced options for Arch Linux'/'Arch Linux, with Linux linux (fallback initramfs)'~35beedf6b757765375e2c50330382305~
"