#!/bin/sh
#THIS IS A GRUB PROXY SCRIPT
'/etc/grub.d/proxifiedScripts/linux' | /etc/grub.d/bin/grubcfg_proxy "+*
-'Arch Linux'~57129b7f9ea4c0fb5e94113481d83747~
+#text
-'SUBMENU' as 'Advanced options for Arch Linux'{-'Advanced options for Arch Linux'/*, -'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-zen'~030badb2c1ad9b683b8dc1d77ca18747~, -'Advanced options for Arch Linux'/'Arch Linux, with Linux linux-zen (recovery mode)'~59fe1d85236ec551bc1c8f3061cef328~, -'Advanced options for Arch Linux'/'Arch Linux, with Linux linux'~56296e207996dda8c6821be1d4b35589~, -'Advanced options for Arch Linux'/'Arch Linux, with Linux linux (recovery mode)'~315ae18500999928d36ac82ea745f7da~}
"